services:

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - api
    restart: always
    volumes:
      - ./frontend/src:/app/src

  api:
    build: ./api
    ports:
      - '8000:8000'
    depends_on:
      - db
    restart: always
    env_file:
      - .env.dev

  db:
    image: postgres
    restart: always
    env_file:
      - .env.dev
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgres/dumps:/postgres/dumps

volumes:
  postgres: